name: Docker Image CI

on:
  push:
    branches: ["sans_rdflib"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        run: |
          docker build -t ghcr.io/epoz/shmarql:$(date +%s) .
          docker push ghcr.io/epoz/shmarql --all-tags
