name: Docker Image CI

on:
  push:
    branches: ["sans_rdflib"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build and Push
        run: |
          docker build -t ghcr.io/shmarql:$(date +%s) .
          docker push ghcr.io/shmarql:$(date +%s)
